@startuml
!define LIGHTYELLOW #FFFACD

skinparam component {
    BackgroundColor LIGHTYELLOW
    BorderColor Black
    FontSize 12
}

skinparam arrow {
    FontSize 9
}

skinparam minlen 2

component "Nodo Politica" as NP
component "Modulo Recuperacion" as MR 
component "Modulo Generacion" as MG
component "Modulo Fusion" as MF

NP .down.> MR : Config\ndinamica
NP .down.> MG : Seleccion\nmodelo
MR .down.> MF : Resultados\nrecuperacion  
MG .down.> MF : Resultados\ngeneracion
MF .up.> NP : Retroalimentacion

@enduml