@startuml 
' Mejora la legibilidad y la calidad de la imagen para documentos.
!theme plain
skinparam {
    dpi 600
    shadowing false
    backgroundColor transparent
    defaultFontName "Arial"
    defaultFontSize 15

    sequence {
        participantBorderColor #2688d4
        participantBackgroundColor #add8e6
        actorBorderColor #2688d4
        actorBackgroundColor #ffdead
    }

    arrow {
        color #2688d4
    }
}


participant "Usuario" as User
participant "Sistema SELF-RAG" as SELFRAGSystem
participant "Retriever Externo" as ExternalRetriever
participant "Base de Conocimiento" as KnowledgeBase

User -> SELFRAGSystem: Envia consulta
activate SELFRAGSystem

loop Hasta generar token de fin
    SELFRAGSystem -> SELFRAGSystem: ¿Recuperar?
    alt Decidir Recuperar
        SELFRAGSystem -> ExternalRetriever: Solicitar recuperacion
        activate ExternalRetriever
        ExternalRetriever -> KnowledgeBase: Recuperar pasajes
        activate KnowledgeBase
        KnowledgeBase --> ExternalRetriever: Pasajes
        deactivate KnowledgeBase
        ExternalRetriever --> SELFRAGSystem: Pasajes
        deactivate ExternalRetriever
        SELFRAGSystem -> SELFRAGSystem: Generar criticas para pasajes
        alt Pasajes Relevantes
            SELFRAGSystem -> SELFRAGSystem: Generar continuacion con pasajes
        else
            SELFRAGSystem -> SELFRAGSystem: Generar continuacion sin pasajes
        end
    else
        SELFRAGSystem -> SELFRAGSystem: Generar siguiente segmento
    end
end

SELFRAGSystem --> User: Envia respuesta final
deactivate SELFRAGSystem

@enduml